export const tablist = [
  {
    id: "AccountTab0",
    tabName: "Account summary",
    index: 0,
    link: "/dashboard/account",
    isDisabled: false,
    heading: "",
    subHeading: "",
  },
  {
    id: "AccountTab1",
    tabName: "Profile",
    index: 1,
    link: "/dashboard/account/profile",
    isDisabled: false,
    heading: "Need to update profile details?",
    subHeading: "Click below to update your personal or address details",
  },
  {
    id: "AccountTab2",
    tabName: "Password",
    index: 2,
    link: "/dashboard/account/password",
    isDisabled: false,
    heading: "Need to update your password?",
    subHeading: "Click below to change your password",
  },
  {
    id: "AccountTab5",
    tabName: "Notification",
    index: 3,
    link: "/dashboard/account/notification",
    isDisabled: false,
    heading: "Manage your notifications & alerts",
    subHeading: "You can choose your preference for alerts and notification",
  },
];
